---
- name: Configure Jenkins Master
  hosts: jenkins_master
  become: true

  tasks:
    - name: Install Docker Dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce docker-ce-cli containerd.io
        state: present

    - name: Pull Jenkins Docker Image
      ansible.builtin.command: docker pull jenkins/jenkins

    - name: Run Jenkins Container
      ansible.builtin.command: docker run -d -p 8080:8080 --name jenkins-master jenkins/jenkins

- name: Configure Deployment Server
  hosts: deployment_server
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Flask Dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

- name: Configure GitLab Server
  hosts: gitlab_server
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull GitLab Docker Image
      shell: docker pull gitlab/gitlab-ce

    - name: Run GitLab Container
      shell: docker run -d -p 8080:80 --name gitlab-server gitlab/gitlab-ce


      
      #ansible-playbook -i '<35.180.120.226>,' -i '<35.180.178.185>,' -i '<51.44.17.30>,' -i '<35.180.54.6>,' capiweather_playbook.yml


